# serveur web
http { 
    # chaque site
    server {
        # port http (lui 'est par default) et 443 pour https
        listen 80;
        # tozt ca pour configure le https
        ssl_protocol TLSv1.3;
        ssl_certificate /etc/ssl/certs/cert.pem;
        ssl_certificate_key /etc/ssl/private/key.pem;
        # pour indiquer quelle dosser contient les fichiers qu'on va utiliser
        location / {

            root /usr/share/nginx/html;
            # fichier par default quqnd on visite
            index index.html;
        }
    }
}