# chaque site
server {
    # port http (lui 'est par default) et 443 pour https
    listen 80;

    return 301 https://$host$request_uri;
    }
server {
    # port https 443 pour https
    listen 443 ssl;
    # tozt ca pour configure le https
    ssl_protocol TLSv1.3;
    ssl_certificate /etc/nginx/ssl/public_certificate.pem;
    ssl_certificate_key /etc/nginx/ssl/private_key.pem;
    # pour indiquer quelle dosser contient les fichiers qu'on va utiliser
    location / {

    proxy_pass http://wordpress:9000;
        
    # Ajouts nécessaires pour le bon fonctionnement d'un proxy
    include fastcgi_params;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    }
}